"""lutz dedup — detect near-duplicate articles via cosine distance clustering (PRISMA step)."""
from __future__ import annotations

import json
from pathlib import Path

import click
from rich.console import Console
from rich.table import Table

from lutz.core.vector_store import VectorStore
from lutz.utils.dedup import find_duplicate_groups
from lutz.utils.project import require_project_root

console = Console()


# ---------------------------------------------------------------------------
# HTML output helper (inline — no extra dependency on html_report module)
# ---------------------------------------------------------------------------


def _generate_dedup_html(groups: list[dict], threshold: float) -> str:
    import html as _html

    n_groups = len(groups)
    n_articles = sum(1 + len(g["duplicates"]) for g in groups)

    rows_html = ""
    for g in groups:
        keep = _html.escape(g["keep"])
        rows_html += (
            f'<tr style="background:#dcfce7">'
            f'<td><strong>{keep}</strong></td>'
            f'<td><span style="background:#166534;color:#fff;padding:2px 8px;border-radius:99px;font-size:0.75rem">KEEP</span></td>'
            f'<td>—</td>'
            f'</tr>\n'
        )
        for dup in g["duplicates"]:
            fn = _html.escape(dup["filename"])
            dist = dup["distance"]
            rows_html += (
                f'<tr>'
                f'<td style="padding-left:2rem">{fn}</td>'
                f'<td><span style="background:#fef3c7;color:#92400e;padding:2px 8px;border-radius:99px;font-size:0.75rem">DUPLICATE</span></td>'
                f'<td style="font-family:monospace">{dist:.6f}</td>'
                f'</tr>\n'
            )

    summary = (
        f"Found {n_groups} duplicate group(s) across {n_articles} articles. No files were deleted."
        if n_groups > 0
        else f"No near-duplicates found (threshold={threshold}). Corpus looks clean."
    )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>lutz — Deduplication Report</title>
  <style>
    *, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
      background: #f8fafc; color: #1e293b; line-height: 1.6;
    }}
    .container {{ max-width: 900px; margin: 0 auto; padding: 2rem 1rem 4rem; }}
    .report-header {{
      background: #1e293b; color: #f1f5f9;
      border-radius: 12px; padding: 2rem; margin-bottom: 2rem;
    }}
    h1 {{ font-size: 1.5rem; font-weight: 700; margin-bottom: 0.5rem; }}
    .logo {{ color: #38bdf8; }}
    .summary {{ background: #fff; border: 1px solid #e2e8f0; border-radius: 10px; padding: 1rem; margin-bottom: 1.5rem; }}
    table {{ width: 100%; border-collapse: collapse; background: #fff; border: 1px solid #e2e8f0; border-radius: 10px; overflow: hidden; }}
    thead th {{ text-align: left; padding: 0.75rem 1rem; background: #f1f5f9; color: #475569; font-size: 0.75rem; text-transform: uppercase; border-bottom: 1px solid #e2e8f0; }}
    tbody td {{ padding: 0.65rem 1rem; border-bottom: 1px solid #f1f5f9; font-size: 0.875rem; }}
    .footer {{ text-align: center; margin-top: 3rem; font-size: 0.8rem; color: #94a3b8; }}
  </style>
</head>
<body>
  <div class="container">
    <header class="report-header">
      <h1><span class="logo">lutz</span> &mdash; Deduplication Report</h1>
      <p>Threshold: {threshold}</p>
    </header>
    <div class="summary">{_html.escape(summary)}</div>
    {"<table><thead><tr><th>Article</th><th>Status</th><th>Cosine distance</th></tr></thead><tbody>" + rows_html + "</tbody></table>" if n_groups > 0 else ""}
    <footer class="footer">Generated by lutz</footer>
  </div>
</body>
</html>
"""


# ---------------------------------------------------------------------------
# Click command
# ---------------------------------------------------------------------------


@click.command()
@click.option(
    "--threshold",
    default=0.05,
    show_default=True,
    type=click.FloatRange(0.0, 2.0),
    help=(
        "Maximum cosine distance for two articles to be considered near-duplicates. "
        "Cosine distance = 1 − cosine_similarity. "
        "0.05 means ≥ 95% cosine similarity. Lower values = stricter matching."
    ),
)
@click.option(
    "--format",
    "output_format",
    default="table",
    show_default=True,
    type=click.Choice(["table", "json", "html"], case_sensitive=False),
    help="Output format: rich table (default), JSON, or HTML.",
)
@click.option(
    "--output",
    "output_path",
    default=None,
    type=click.Path(dir_okay=False, path_type=Path),
    help=(
        "Save output to this file path instead of printing to stdout. "
        "For --format table, saves as plain text."
    ),
)
def dedup(
    threshold: float,
    output_format: str,
    output_path: Path | None,
) -> None:
    """Detect near-duplicate articles in the vector store (PRISMA deduplication step).

    \b
    Algorithm
      1. Load mean embeddings per article from the vector store.
      2. Compute pairwise cosine distances between article embeddings (O(n²) on
         article count, not chunk count — tractable for typical corpora).
      3. Cluster articles with cosine_distance < threshold using Union-Find.
      4. For each cluster, elect one representative to keep (sorted-first for
         determinism) and list the others as duplicates.
      5. Report groups for human review — NO files are deleted automatically.

    \b
    Output formats
      table  — Rich table in the terminal (default)
      json   — JSON array of duplicate groups
      html   — Self-contained HTML report

    \b
    Examples
      lutz dedup
      lutz dedup --threshold 0.03
      lutz dedup --format json
      lutz dedup --format html --output dedup_report.html
      lutz dedup --format json --output dedup.json
    """
    project_root = require_project_root()
    store = VectorStore(project_root / ".lutz" / "vector_store")
    article_embeddings = store.get_embeddings_by_article()

    if not article_embeddings:
        console.print(
            "[bold red]Error:[/] Vector store is empty or has no articles.\n"
            "Run [bold]lutz vectorize[/] first to index your articles."
        )
        raise click.Abort()

    n_articles = len(article_embeddings)
    console.print(
        f"[dim]Scanning [cyan]{n_articles}[/] article(s) "
        f"with threshold=[cyan]{threshold}[/]...[/]"
    )

    groups = find_duplicate_groups(article_embeddings, threshold=threshold)
    n_groups = len(groups)
    n_dup_articles = sum(1 + len(g["duplicates"]) for g in groups)

    # ---- Build output content ------------------------------------------------

    if output_format == "json":
        # Add group_id field for the JSON format
        json_groups = [
            {"group_id": i + 1, "keep": g["keep"], "duplicates": g["duplicates"]}
            for i, g in enumerate(groups)
        ]
        content = json.dumps(json_groups, ensure_ascii=False, indent=2)

        if output_path is not None:
            output_path.write_text(content, encoding="utf-8")
            console.print(f"[green]Saved to[/] {output_path}")
        else:
            # Print JSON to stdout and summary to stderr to allow piping
            click.echo(content)

    elif output_format == "html":
        content = _generate_dedup_html(groups, threshold)

        if output_path is not None:
            output_path.write_text(content, encoding="utf-8")
            console.print(f"[green]Saved to[/] {output_path}")
        else:
            click.echo(content)

    else:
        # table (default)
        if n_groups == 0:
            console.print(
                f"\n[green]No near-duplicates found[/] (threshold={threshold}). "
                "Corpus looks clean."
            )
        else:
            table = Table(
                title=f"Near-duplicate groups (threshold={threshold})",
                show_lines=True,
                header_style="bold cyan",
            )
            table.add_column("Group", justify="right", style="dim", width=6)
            table.add_column("Article")
            table.add_column("Status")
            table.add_column("Cosine distance", justify="right")

            for i, g in enumerate(groups, 1):
                table.add_row(
                    str(i),
                    g["keep"],
                    "[green]KEEP[/]",
                    "—",
                )
                for dup in g["duplicates"]:
                    table.add_row(
                        "",
                        f"  {dup['filename']}",
                        "[yellow]DUPLICATE[/]",
                        f"{dup['distance']:.6f}",
                    )

            if output_path is not None:
                # Save plain text representation
                from io import StringIO
                from rich.console import Console as RichConsole
                buf = StringIO()
                plain_console = RichConsole(file=buf, highlight=False, markup=False)
                plain_console.print(table)
                output_path.write_text(buf.getvalue(), encoding="utf-8")
                console.print(f"[green]Saved to[/] {output_path}")
            else:
                console.print(table)

    # ---- Summary message (always printed to console) -------------------------
    if n_groups > 0:
        console.print(
            f"\n[bold]Found {n_groups} duplicate group(s) across "
            f"{n_dup_articles} article(s). "
            f"[red]No files were deleted.[/][/bold]"
        )
    else:
        if output_format != "table":
            console.print(
                f"\n[green]No near-duplicates found[/] (threshold={threshold}). "
                "Corpus looks clean."
            )
